### ISSUE TITLE
Pseudo-Labels Discrepancy Minimization

### ISSUE THREAD

**Issue by 610v4nn1** [antoinedemathelin/dbal#1]
Hi,
I would like to verify that this algorithm https://github.com/antoinedemathelin/dbal/blob/master/dbal/query_methods.py#L77
is exactly what in your paper is called "Pseudo-Labels Discrepancy Minimization" (Appendix F3).
Thanks.

**Comment by antoinedemathelin** [comment]
Hi 610v4nn1,
Indeed MinDiscrepancyGreedy refers to "Pseudo-Labels Discrepancy Minimization".
Best,
