### ISSUE TITLE
MinDiscrepancyGreedy has been removed

### ISSUE THREAD

**Issue by 610v4nn1** [antoinedemathelin/dbal#4]
I see that the `MinDiscrepancyGreedy` class has been removed and the algorithm has been removed also from the new version of the paper. Is there any specific reason for this choice?
Should people avoid leveraging that code? was there a problem with the method?

**Comment by antoinedemathelin** [comment]
Hello 610v4nn1,
Indeed we removed MinDiscrepancyGreedy from the new version of the paper. There is no problem with the algorithm, however, as it has been noticed by reviewers, MinDiscrepancyGreedy did not bring much improvement compared to K-medoids. We then choose to focus on KMedoids, KMedoidsAccelerated and their weighted-embedded versions (see https://github.com/antoinedemathelin/dbal/blob/master/notebooks/Digits_preprocessing.ipynb)
Best,

**Comment by 610v4nn1** [comment]
Thanks for the clarification.
